language: node_js
node_js:
  - "6"
  - "7"
before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r https://registry.npmjs.org
deploy:
  provider: npm
  email: huttarichard@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true